kind = "api"
  previewPath = "/api"
  title = "API Server"
  version = "1.0.0"
  id = "3B4_FFSkEVBkAeYMFRJ2e"

  [[services]]
  localPort = 3000
  name = "API Server"
  paths = ["/api", "/health"]

  [services.development]
  run = "node /home/runner/workspace/MineFleet/index.js"

  [services.production]

  [services.production.run]
  args = ["node", "/home/runner/workspace/MineFleet/index.js"]
  